### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [denis-shvetcov/cmdJava#1]
1. https://github.com/denis-shvetcov/cmdJava/blob/53eb4496c61de815154a6e8116199a4e5ad630d7/src/main/Tail.java#L26-L30 Это тоже часть разбора аргументов, так что стоит это вынести в `TailLauncher`.
1. https://github.com/denis-shvetcov/cmdJava/blob/53eb4496c61de815154a6e8116199a4e5ad630d7/src/main/Tail.java#L49 Это тоже.
1. При чтении из консоли нужно читать до конца ввода, то есть столько строк, сколько пользователь захочет ввести, а не заканчивать считывание раньше времени.
1. Вообще у Вас много дублирования кода. Можно значительно уменьшить размер кода, если заметить, что консоль ни для чтения, ни для вывода ничем от файла не отличается. Из `System.in` можно сделать `BufferedReader`, а из `System.out` - `BufferedWriter`, а потом работать так, как будто это файлы. Лучше всего, на мой взгляд, будет в `Tail` передавать `BufferedWriter` и  `BufferedReader`, а создавать их в `TailLauncher` в зависимости от аргументов.

**Comment by denis-shvetcov** [comment]
1,2. Перенес проверки в лаунчер.
3. Добавил в методы стоп-слово.
4. Добавил реализацию потоков в зависимости от полученных аргументов.

**Comment by maximpetrov** [comment]
1. Повторюсь, чтение из консоли должно работать так же, как и чтение из файла, то есть просто до конца ввода (Ctrl+D в консоли) без всяких стоп слов.
1. Сейчас У Вас вообще нельзя запустить программу так, чтобы она читала с консоли.
1. `BufferedReader` тоже следует создавать снаружи.
1. Исключения не стоит ловить там, где с ними нельзя сделать (вывод сообщения не считается)
1. В тесте не нужно создавать экземпляр класса `TailLauncher`, ведь `main` - статический метод.
1. Собирать файл в строку через неизменяемый `String` - плохо. Если нужно именно собирать постепенно, то используйте `StringBuilder`, если нужно перевести список в строку, используйте `String.join()`
1. Вообще, не совсем честно заменять переносы строк на `'\n'`, ведь он используется как перенос строки только в UNIX-подобных ОС. Это было бы не так критично при работе в режиме "отрезания" строк (в нём Вы так и не делаете), но в режиме "отрезания" символов это приводит к некорректному подсчёту символов.
1. В идеале, перенос в конце выходного файла должен быть, если он есть во входном файле. Если использовать `readLine()`, то нельзя понять был ли перенос в конце файла. В таком случае, лучше всегда ставить перенос строки в конце файла, так как это соответствует определению текстового файла в POSIX.
1. (Необязательное замечание) Было бы совсем хорошо, если бы Вы не хранили весь файл в памяти, он ведь, чисто теоретически, может и несколько гигабайт весить. Можно, например, считывать файл построчно и хранить не больше нужного числа последних считанных строк (для этого стоит использовать какую-нибудь реализацию `Queue`). Аналогично можно поступить с символами.

**Comment by denis-shvetcov** [comment]
1. Убрал стоп слово.
2. Вновь  читает с консоли.
3. Создается снаружи, в зависимости от наличия `output` файла.
4. Не совсем понял насчет исключений. Вы имеете в виду, что нужно добавить их к методу?
5. Метод теперь вызывается без создания экземпляра класса.
6. Теперь текст не строится из `String` , я реализовал интерфейс `Deque`.
7. Теперь вместо `'n'` используется `System.lineSeparator()` . В таком случае, раз у разных систем разные способы переноса строк, то теперь я решил не считать символы переноса.

**Comment by denis-shvetcov** [comment]
1. Убрал стоп слово.
2. Вновь читает с консоли.
3. Создается снаружи, в зависимости от наличия `output` файла.
4. Не совсем понял насчет исключений. Вы имеете в виду, что нужно добавить их к методу?
5. Метод теперь вызывается без создания экземпляра класса.
6. Теперь текст не строится из `String`, реализован интерфейс `Deque`.
7. Вместо `'\n'` используется `System.lineSeparator()` . В таком случае, раз у разных систем разные способы переноса строк, то теперь я решил не считать символы переноса, чтобы избежать несовпадение при подсчете символов в разных системах. 
8. В конце файла осуществлен перенос строки.
9. Реализован метод `Deque`, с ним даже проще.

**Comment by maximpetrov** [comment]
1. Да, лучше добавить `throws` в методах `Tail`, а ловить уже в `main`. Кстати, в случае, когда Вы хотите завершить программу в случае исключения, лучше вызывать `System.exit()` с ненулевым кодом.
1. Как раз в режиме "отрезания" символов не стоит выкидывать переносы строк, ведь это тоже символы. Ваше замечание по поводу несовпадения при подсчёте символов в разных системах не совсем верное. Да, при создании файла текстовые редакторы используют (как правило, но не всегда) для переноса строки символ(ы) принятые в ОС. Но эти символы хранятся в файле и не поменяются, если открыть этот же файл в другой ОС, так что никакого несовпадения при подсчёте символов не будет.
1. Вообще в тестах было бы логичнее вместо генерации ожидаемого содержимого, просто сделать файлы с соответствующим содержимым, а потом сравнивать содержимое этих файлов. С учётом предыдущего пункта лучше будет сделать два метода для сравнения файлов: посимвольный (без `readLine()`) для проверки режима `-c` и построчный (просто сравнить два списка без `String.join`) для `-n`.

**Comment by denis-shvetcov** [comment]
Как я понял, перенос строки занимает два символа, но в разных OC они
разные, правильно?

**Comment by denis-shvetcov** [comment]
А что делать с возвратом каретки? Его считать за символ?

**Comment by maximpetrov** [comment]
Следует считать все символы, которые есть в файле. То есть в Windows новая строка обозначается двумя символами (возврат каретки(\r) и перенос строки(\n)), в других системах, как правило, одним (либо \n, либо \r).

**Comment by denis-shvetcov** [comment]
Тогда понятно, я это для тестов спрашиваю, так как в Windows , по идее,
будет меньше "смысловых" символов: букв, чисел и тд., тк перенос занимает
два символа.

**Comment by maximpetrov** [comment]
Если Вы редактируете текстовые файлы через Idea, то там указывается для каждого файла, что использовать для переноса строки (в правом нижнем углу).

**Comment by denis-shvetcov** [comment]
Увидел, спасибо

**Comment by denis-shvetcov** [comment]
1. Вынес исключения в `main`.
2. Считаются все символы.
3. Сделал два метода для сравнения строк и символов.

**Comment by maximpetrov** [comment]
Судя по всему, Вы забыли запушить изменения

**Comment by denis-shvetcov** [comment]
Форс-мажор

**Comment by maximpetrov** [comment]
Верните `public` для конструктора `Tail` и метода `cutTail`.

**Comment by denis-shvetcov** [comment]
Вернул
